dist: trusty
sudo: required 

language: cpp
cache:
  - ccache
  - pip
  - directories:
    - $HOME/opt
  
install:
  - sudo apt update
  - sudo apt install mpi-default-bin mpi-default-dev
  - sudo apt install libfftw3-dev gsl-bin libgsl0-dev libboost-serialization-dev
  - sudo apt-get update
  - pyenv global 3.6
  - pip3 install PyYAML
  - git clone --bare https://github.com/plumed/plumed2.git
# pick newest release branch (alphabetic, will fail at v2.10)
  - export PLUMED_LATEST_VERSION="$(cd plumed2.git ; git branch | sed "s/^ *//" | grep '^v2\.[0-9]$' | tail -n 1)"
  - export PATH="$HOME/opt/bin:$PATH"
  - export LD_LIBRARY_PATH="$HOME/opt/lib:$LD_LIBRARY_PATH"
  - sudo ln -s ccache /usr/local/bin/mpic++
  - export PATH=/usr/lib/ccache:${PATH}
  - ccache -s
  - .travis/install.xdrfile
# version=master or version=f123f12f3 to select a specific version
  - CXX="mpic++" .travis/install.plumed version=$PLUMED_LATEST_VERSION repo=$PWD/plumed2.git
# GB: in addition, we install master version as plumed_master
  - CXX="mpic++" .travis/install.plumed version=master suffix=_master repo=$PWD/plumed2.git
  - ccache -s

script:
  - python3 --version
  - python3 nest.py
  - bash .travis/push $(find . -name "*.md") _config.yml _layouts _data Contribute.html
